### ISSUE TITLE
panic: send on closed channel (when proxy closes connection)

### ISSUE THREAD

**Issue by mvrhov** [rogchap/wombat#53]
goroutine 104 [running]:
wombat/internal/app.(*transportCreds).ClientHandshake(0xc0070bb240, 0x104e840, 0xc007182ed0, 0xc0004de300, 0x16, 0x1057140, 0xc0004b4908, 0x0, 0x0, 0x103ed20, ...)
	/home/runner/work/wombat/wombat/internal/app/client.go:31 +0x16e
google.golang.org/grpc/internal/transport.newHTTP2Client(0x104e800, 0xc007180300, 0x104e780, 0xc0070cc740, 0xc0004de300, 0x16, 0xc0004de300, 0x16, 0x0, 0x0, ...)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.33.1/internal/transport/http2_client.go:225 +0x62c
google.golang.org/grpc/internal/transport.NewClientTransport(...)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.33.1/internal/transport/transport.go:577
google.golang.org/grpc.(*addrConn).createTransport(0xc0002c8840, 0xc0004de300, 0x16, 0xc0004de300, 0x16, 0x0, 0x0, 0x0, 0x0, 0xc0070af8c0, ...)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.33.1/clientconn.go:1297 +0x428
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc0002c8840, 0xc0070cc000, 0x1, 0x1, 0xc00f8284ee6e4089, 0x87523494e, 0x17c3d40, 0x1058de0, 0xc0001f0000, 0x0, ...)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.33.1/clientconn.go:1227 +0x3c8
google.golang.org/grpc.(*addrConn).resetTransport(0xc0002c8840)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.33.1/clientconn.go:1142 +0x23f
created by google.golang.org/grpc.(*addrConn).connect
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.33.1/clientconn.go:825 +0x12a

**Comment by rogchap** [comment]
Do you have any steps that I can reproduce?

**Comment by mvrhov** [comment]
I have a traefik in docker which terminates https and then proxies to go grpc via h2c (cleartext http2). When I terminate the composer which in turn terminates the traefik the wombat then dies. Do you need the traefik configuration... But this means certificate setup etc...

**Comment by rogchap** [comment]
Possibly duplicates #60 and fixed in #61
